In [166]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [167]:
df = pd.read_csv("Data_Science_Jobs.csv")
df = df[df["Role_Category"] == "Analytics & BI"]
df = df[["Skill1", "Skill1", "Skill2", "Skill3", "Skill4", "Skill5", "Skll6", "Skill7", "Skill8" ]]
df

,Skill1,Skill1,Skill2,Skill3,Skill4,Skill5,Skll6,Skill7,Skill8
0,IT Skills,IT Skills,Python,Data Science,Machine Learning,Tableau,analytics,deep learning,algorithms
6,IT Skills,IT Skills,Python,Machine Learning,Artificial Intelligence,Data Science,Predictive Modeling,Data Scientist,Artificial Intelligence
7,Regression Algorithms,Regression Algorithms,NLP,Data Scientist,Artificial Intelligence,Data Modeling,Data Warehousing,Data Analytics,ETL
12,IT Skills,IT Skills,Data Science,Machine Learning,Big Data,Data Transformation,Automation,Business Intelligence,Statistical modeling
15,IT Skills,IT Skills,Python,Cloud,Oracle,AWS,Tableau,Power BI,DataLake
...,...,...,...,...,...,...,...,...,...
539,Data Science,Data Science,Excel,Data Analysis,Data Visualization,SPSS,Market Analysis,Statistical Analysis,Competitive Analysis
541,Data Science,Data Science,R,C,Data Scientist,Statistical Analyst,Machine Learning,Algorithm,Python
547,Data Science,Data Science,Predictive Modeling,R,Genomics,operations research,AI,Genetics,Machine Learning
548,Data Science,Data Science,Predictive Modeling,R,Genomics,operations research,AI,Genetics,Machine Learning
564,Predictive Modeling,Predictive Modeling,Logistic Regression,SAS,Artificial Intelligence,Machine Learning,Analytics,Data Science,Regression Analysis

In [168]:
count = 0
liste_skills = []
for _, row in df.iterrows():
    for item in row:
        count+=1
        if item not in liste_skills:
            liste_skills.append(item)

In [169]:
dict_skills = {item: 0 for item in liste_skills}

In [170]:
for _, row in df.iterrows():
    for item in row:
        dict_skills[item] += 1/1179*100

In [171]:
top_10 = dict(sorted(dict_skills.items(), key=lambda item: item[1], reverse=True)[:15])

In [172]:
top_10

{'Data Science': 168,
 'IT Skills': 118,
 'Machine Learning': 62,
 'Python': 56,
 nan: 48,
 'Big Data': 30,
 'Data Scientist': 29,
 'Artificial Intelligence': 26,
 'R': 25,
 'Predictive Modeling': 21,
 'Data Management': 20,
 'Tableau': 19,
 'NLP': 16,
 'Cloud': 16,
 'Java': 16}

In [173]:
count

1179